//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirTransfer.Resources.Languages {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FantasyRemoteCopy.UI.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Device type.
        /// </summary>
        internal static string DeviceType {
            get {
                return ResourceManager.GetString("DeviceType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Global refresh.
        /// </summary>
        internal static string GlobalRefresh {
            get {
                return ResourceManager.GetString("GlobalRefresh", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Input your device name.
        /// </summary>
        internal static string InputYourDeviceName {
            get {
                return ResourceManager.GetString("InputYourDeviceName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Input your login name.
        /// </summary>
        internal static string InputYourLoginName {
            get {
                return ResourceManager.GetString("InputYourLoginName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Modify Path.
        /// </summary>
        internal static string ModifyPath {
            get {
                return ResourceManager.GetString("ModifyPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nick of name:.
        /// </summary>
        internal static string NickOfName {
            get {
                return ResourceManager.GetString("NickOfName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No device has been found. Please try to click the &apos;Global refresh&apos; .Takes a long Time.
        /// </summary>
        internal static string NoDeviceHasBeenFoundPleaseTryToClickTheGlobalRefreshTakesALongTime {
            get {
                return ResourceManager.GetString("NoDeviceHasBeenFoundPleaseTryToClickTheGlobalRefreshTakesALongTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save Path.
        /// </summary>
        internal static string SavePath {
            get {
                return ResourceManager.GetString("SavePath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
    }
}